const routes = {
    home: '/',
    following: '/following',
    products: '/products/brand/:brandName',
    genres: '/products/genre/:brandName/:genreName',
    new: '/products/new/:brandName',
    productdiscount: '/products/special/:brandName',
    // brandConverse: '/products/Converse',
    // brandVans: '/products/Vans',
    // brandPalladium: '/products/Palladium',
    // brandKswiss: '/products/Kswiss',
    // brandNike: '/products/Nike',
    specialprice: '/specialprice',
    profile: '/:nickname',
    upload: '/upload',
    search: '/search',
    live: '/live',
    detailproduct: '/product/:productId',
    login: '/login',
    register: '/register',
    forget: '/forget',
    account: '/account',
    cart: '/cart',
    payment: '/payment',
    order: '/order',
    orderwait: '/order/wait',
    ordertransport: '/order/transport',
    ordercompletion: '/order/completion',
    ordercanceled: '/order/canceled',
};

export default routes;
