const routes = {
    home: '/IT-Sneaker/',
    following: '/IT-Sneaker/following',
    products: '/IT-Sneaker/products/brand/:brandName',
    genres: '/IT-Sneaker/products/genre/:brandName/:genreName',
    new: '/IT-Sneaker/products/new/:brandName',
    productdiscount: '/IT-Sneaker/products/special/:brandName',
    // brandConverse: '/products/Converse',
    // brandVans: '/products/Vans',
    // brandPalladium: '/products/Palladium',
    // brandKswiss: '/products/Kswiss',
    // brandNike: '/products/Nike',
    specialprice: '/IT-Sneaker/specialprice',
    profile: '/IT-Sneaker/:nickname',
    upload: '/IT-Sneaker/upload',
    search: '/IT-Sneaker/search',
    live: '/IT-Sneaker/live',
    detailproduct: '/IT-Sneaker/product/:productId',
    login: '/IT-Sneaker/login',
    register: '/IT-Sneaker/register',
    forget: '/IT-Sneaker/forget',
    account: '/IT-Sneaker/account',
    cart: '/IT-Sneaker/cart',
    payment: '/IT-Sneaker/payment',
    order: '/IT-Sneaker/order',
    orderwait: '/IT-Sneaker/order/wait',
    ordertransport: '/IT-Sneaker/order/transport',
    ordercompletion: '/IT-Sneaker/order/completion',
    ordercanceled: '/IT-Sneaker/order/canceled',
};

export default routes;
